# Generated by Django 3.2.6 on 2022-10-05 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('count', models.IntegerField(default=0, verbose_name='Número de visitas al sitio web')),
            ],
            options={
                'verbose_name': 'Estadísticas de visitas diarias al sitio web',
                'verbose_name_plural': 'Estadísticas de visitas diarias al sitio web',
            },
        ),
        migrations.CreateModel(
            name='RegistroTotalDeIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], max_length=100, verbose_name='mes')),
                ('total_x_afiliaciones', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_x_pagos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_x_compras', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_actual', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Ingreso del mes: ',
                'verbose_name_plural': 'Ingresos totales al Mes',
            },
        ),
        migrations.CreateModel(
            name='TotalGeneralDeIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Ingresos totales a la Fecha',
                'verbose_name_plural': 'Ingresos totales a la Fecha',
            },
        ),
        migrations.CreateModel(
            name='Userip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='Dirección IP')),
                ('count', models.IntegerField(default=0, verbose_name='Visitas')),
            ],
            options={
                'verbose_name': 'Acceder a la información del usuario',
                'verbose_name_plural': 'Acceder a la información del usuario',
            },
        ),
        migrations.CreateModel(
            name='VisitNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Total de visitas al sitio web')),
            ],
            options={
                'verbose_name': 'Total de visitas al sitio web',
                'verbose_name_plural': 'Total de visitas al sitio web',
            },
        ),
        migrations.CreateModel(
            name='RolDeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_vendedor', models.BooleanField(default=False, verbose_name='Vendedor')),
                ('es_administrativo', models.BooleanField(default=False, verbose_name='Administrativo')),
                ('es_cobrador', models.BooleanField(default=False, verbose_name='Cobrador')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDeUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_afiliaciones', models.IntegerField(default=0)),
                ('total_pagos', models.IntegerField(default=0)),
                ('total_cupones', models.IntegerField(default=0)),
                ('total_compras', models.IntegerField(default=0)),
                ('total_comision_x_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_comision_x_semana', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='actualizado')),
                ('usuario', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad del usuario',
                'verbose_name_plural': 'Regis. Actividad x Usuarios',
            },
        ),
        migrations.CreateModel(
            name='PagosxMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(default='10/2022', max_length=10, verbose_name='Mes')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('inf_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='sitio.pago')),
            ],
            options={
                'verbose_name': 'Pagos x mes',
                'verbose_name_plural': 'Pagos del Mes',
            },
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibido', models.BooleanField(default=False)),
                ('msj', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to=settings.AUTH_USER_MODEL)),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajeria interna',
            },
        ),
        migrations.CreateModel(
            name='ComisionesDeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcen_x_venta', models.IntegerField(default=0)),
                ('porcen_x_afiliacion', models.IntegerField(default=0)),
                ('porcen_x_cobros', models.IntegerField(default=0)),
                ('rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='panel.roldeusuario')),
            ],
            options={
                'verbose_name': 'Comisiones x rol',
                'verbose_name_plural': 'Comisiones del Staff',
            },
        ),
    ]
