# Generated by Django 3.2.6 on 2022-10-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='fecha',
        ),
    ]
