# Generated by Django 3.2.6 on 2022-10-05 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_remove_mensajes_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
